repos:
- repo: local
  hooks:
  - id: mypy-trspecfit
    name: mypy (trspecfit)
    entry: python -m mypy --cache-dir=nul src/trspecfit
    language: system
    pass_filenames: false
    stages: [pre-commit]

  - id: pytest
    name: pytest
    entry: python -m pytest -q
    language: system
    pass_filenames: false
    stages: [pre-commit]
