repos:
- repo: local
  hooks:
  - id: mypy-trspecfit
    name: mypy (trspecfit)
    entry: mypy --no-incremental src/trspecfit
    language: python
    additional_dependencies:
      - .[dev]
    pass_filenames: false
    stages: [pre-commit]

  - id: pytest
    name: pytest
    entry: pytest -q
    language: python
    additional_dependencies:
      - .[dev]
    pass_filenames: false
    stages: [pre-commit]
