repos:
- repo: local
  hooks:
  - id: mypy-trspecfit
    name: mypy (trspecfit)
    entry: mypy --no-incremental src/trspecfit
    language: python
    additional_dependencies:
      - .
      - mypy
    pass_filenames: false
    stages: [pre-commit]
